// <auto-generated />
using System;
using JobApplicationTracker.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobApplicationTracker.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobApplicationTracker.Api.Features.Applications.Domain.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("AppliedOn")
                        .HasColumnType("date");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("JobPostingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NextActionDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("NextActionDueAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("NextActionDueAt");

                    b.HasIndex("Status", "UpdatedAt")
                        .IsDescending(false, true);

                    b.ToTable("JobApplications", null, t =>
                        {
                            t.HasCheckConstraint("CK_JobApplications_NextActionPair", "([NextActionDescription] IS NULL AND [NextActionDueAt] IS NULL) OR ([NextActionDescription] IS NOT NULL AND [NextActionDueAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_JobApplications_Status", "[Status] IN ('Saved', 'Applied', 'Screening', 'Interview', 'Offer', 'Rejected', 'Withdrawn')");
                        });
                });

            modelBuilder.Entity("JobApplicationTracker.Api.Features.Applications.Domain.StatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId", "ChangedAt");

                    b.ToTable("StatusChanges", null, t =>
                        {
                            t.HasCheckConstraint("CK_StatusChanges_DifferentStatuses", "[PreviousStatus] IS NULL OR [PreviousStatus] <> [NewStatus]");

                            t.HasCheckConstraint("CK_StatusChanges_NewStatus", "[NewStatus] IN ('Saved', 'Applied', 'Screening', 'Interview', 'Offer', 'Rejected', 'Withdrawn')");

                            t.HasCheckConstraint("CK_StatusChanges_PreviousStatus", "[PreviousStatus] IS NULL OR [PreviousStatus] IN ('Saved', 'Applied', 'Screening', 'Interview', 'Offer', 'Rejected', 'Withdrawn')");
                        });
                });

            modelBuilder.Entity("JobApplicationTracker.Api.Features.Applications.Domain.StatusChange", b =>
                {
                    b.HasOne("JobApplicationTracker.Api.Features.Applications.Domain.JobApplication", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApplicationTracker.Api.Features.Applications.Domain.JobApplication", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
